services:
  backend:
    build: .
    container_name: naxos-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # db:
  #   image: postgres:15-alpine
  #   container_name: naxos-postgres
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: exist
  #     POSTGRES_DB: bolle
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
